config/routes.rb
Taskboard::Application.routes.draw do
  resources :product_owners

  resources :projects

  resources :users

  resources :tasks do
    member do
      get 'set_archived' => :set_archived
      post 'generate_sprint_number' => :generate_sprint_number
    end
    collection do
      match :stories
      match :ongoing
      match :archived
      match :deployed
    end    
  end  
    
  root :to => 'tasks#index'

  match '/tasks/' => 'tasks#index'

  match '/task/new' => 'tasks#new'

  match '/task/:id/update/status' => 'tasks#update_position'
  

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :estimate, :title, :status, :person_id, :archived, :project_id, :sprint_number, :wip_started_date, :completed_at, :tested_at, :deployed_at, :requested_by, :urgent
  belongs_to :owner, :class_name => "User", :foreign_key => :person_id
  belongs_to :project
  belongs_to :requestor, :class_name => "ProductOwner", :foreign_key => :requested_by

  # Named scopes
  scope :active, where('sprint_number IS NOT NULL')
  scope :archived, where(:archived => true)
  scope :current, where('archived = 0 OR archived IS NULL')
  scope :future, where('sprint_number = 0 OR sprint_number IS NULL')
  scope :ready, where(:status => 1).where('archived = 0 OR archived IS NULL').current
  scope :inprogress, where(:status => 2).where('archived = 0 OR archived IS NULL').order(:updated_at).current
  scope :completed, where(:status => 3).where('archived = 0 OR archived IS NULL').order(:updated_at).current
  scope :tested, where(:status => 4).where('archived = 0 OR archived IS NULL').order(:updated_at).current
  scope :deployed, where(:status => 5).where('archived = 0 OR archived IS NULL').order(:updated_at).current
  
  # Callback methods
  after_create :check_urgent
  
  def check_urgent
    if self.urgent == true
      sprint_number = Time.now.strftime("%U%Y").to_i
      self.update_attributes(:sprint_number => sprint_number)
    end  
  end  
  
  def generate_sprint_number
    self[:sprint_number] = Time.now.strftime("%U%Y").to_i
  end
  
  private
    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.active
    @readytasks = @tasks.ready
    @progresstasks = @tasks.inprogress.order(:updated_at)
    @completedtasks = @tasks.completed.order(:updated_at)
    @testedtasks = @tasks.tested.order(:updated_at)
    @deployedtasks = @tasks.deployed.order(:updated_at)
    if Task.last.nil?
      @current_sprint = Time.now.strftime("%U%Y").to_i
    else  
      @current_sprint = @tasks.last.sprint_number
    end  

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to stories_tasks_path, :notice => 'Task was successfully created.' }
        #format.json { render :json => @task, :status => :created, :location => @task }
      else
        format.html { render :action => "new" }
        format.json { render :json => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to tasks_url, :notice => 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  #PUT /task/update/status
  def update_position
    task = Task.find(params[:id])
    newstatus = params[:status].to_i      
    logger.debug(newstatus)
    if newstatus == 2 && task.wip_started_date.nil?
      task.wip_started_date = Time.now
    elsif newstatus == 3
      task.completed_at = Time.now 
    elsif newstatus == 4
      task.tested_at = Time.now 
    elsif newstatus == 5
      task.deployed_at = Time.now 
    end
    if newstatus != task.status
      task.status = newstatus
      task.save
      respond_to do |format|
        format.html {redirect_to :back}
      end
    else
      respond_to do |format|
        format.html {redirect_to :back}
      end
    end     
  end
  
  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
  
  def set_archived
    @task = Task.find(params[:id])
    @task.update_attributes(:archived => true)

    respond_to do |format|
      format.html { redirect_to tasks_url }
    end
  end
  
  def generate_sprint_number
    @task = Task.find(params[:id])
    sprint_number = Time.now.strftime("%U%Y").to_i
    estimate = params[:estimate][:estimate_a]
    person_id = params[:person][:person_id]
    @task.update_attributes(:sprint_number => sprint_number, :estimate => estimate ,:person_id => person_id)

    respond_to do |format|
      format.html { redirect_to tasks_url }
    end
  end
  
  def stories
    @tasks = Task.future
  end
  
  def ongoing
    @tasks = Task.active
    @readytasks = @tasks.ready
    @progresstasks = @tasks.inprogress.order(:updated_at)
    @completedtasks = @tasks.completed.order(:updated_at)
    @testedtasks = @tasks.tested.order(:updated_at)
    if Task.last.nil?
      @current_sprint = Time.now.strftime("%U%Y").to_i
    else  
      @current_sprint = @tasks.last.sprint_number
    end  

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tasks }
    end
  end
  
  def deployed
    @deployedtasks = Task.active.deployed.order(:updated_at)
  end
  
  def archived
    @tasks = Task.archived.order('updated_at desc')
  end        
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Owner" %><br />
    <%= f.select(:person_id, User.all.collect{|c| [c.name, c.id] }) %>
  </div><br/>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :estimate %><br />
    <%= f.number_field :estimate %>
  </div>
  <div class="field">
    <%= f.label :requested_by %><br />
    <%= f.select(:requested_by, ProductOwner.order('name').collect{|c| [c.name, c.id] }) %>
  </div><br/>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.select(:project_id, Project.order('name').collect{|c| [c.name, c.id] }) %>
  </div><br/>	
  <div class="field">
    <%= f.check_box :urgent %>
    <%= f.label :urgent, "Urgent?" %>
  </div><br/>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/archived.html.erb
<script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
<script src="http://code.jquery.com/ui/1.8.21/jquery-ui.min.js"></script>
<script src="jquery.ui.touch-punch.min.js"></script>

<%= image_tag("ncm_logo.jpg", :style => "width: 44px; margin-top: 10px;") %>
<div style="position: absolute; margin-top: -70px; margin-left: 107px;"><h2>NCM Manila</h2></div>
<div style="position: absolute; margin-top: -28px; margin-left: 109px;"><h4>Web Developers</h4></div>
<div style="position: absolute; margin-top: -48px; margin-left: 50px;">
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple117/v4/a6/d2/2c/a6d22ca4-5b4d-a1de-03ac-6a67a81b07fe/source/512x512bb.jpg" style="width:51px;height:51px;">
</div>
<br/><br/>
<h2>&nbsp;Listing Archived Tasks</h2>
<div id="divTasks" style="margin-left: 20px; margin-right: 20px;">
  <div class="center">
	<table class="table table-striped table-hover ">  
	  <tr class="warning">
	    <th>Title</th>
		<th>Description</th>
		<th>Project</th>
		<th>Requested By</th>
		<th>Owner</th>
		<th>Archived at</th>
	  </tr>  
      <tbody>
	    <% @tasks.each do |task| %> 	  
          <tr>
		    <td><%= link_to task.title, task_path(task) %></td>
			<td><%= task.description %></td>
			<td><%= task.project.name unless task.project.nil? %></td>
			<td><%= task.requestor.name unless task.requestor.nil?  %></td>
			<td><%= task.owner.name unless task.owner.nil?  %></td>
			<td><%= task.updated_at.strftime("%d %B, %I:%M%p,%a") %></td>		
          </tr>
		<% end %>  
      </tbody>
    </table>
  </div>
</div>

app/views/tasks/deployed.html.erb
<script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
<script src="http://code.jquery.com/ui/1.8.21/jquery-ui.min.js"></script>
<script src="jquery.ui.touch-punch.min.js"></script>

<%= image_tag("ncm_logo.jpg", :style => "width: 44px; margin-top: 10px;") %>
<div style="position: absolute; margin-top: -70px; margin-left: 107px;"><h2>NCM Manila</h2></div>
<div style="position: absolute; margin-top: -28px; margin-left: 109px;"><h4>Web Developers</h4></div>
<div style="position: absolute; margin-top: -48px; margin-left: 50px;">
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple117/v4/a6/d2/2c/a6d22ca4-5b4d-a1de-03ac-6a67a81b07fe/source/512x512bb.jpg" style="width:51px;height:51px;">
</div>
<br/><br/>
<h2>&nbsp;Deployed Tasks</h2>
<br/>
<% if @deployedtasks.count > 0 %>
<div id="divTasks" style="margin-left: 20px; margin-right: 20px;">
  <div class="center">
	<table class="table table-striped table-hover ">  
	  <tr class="warning">
	    <th width=20%>Title</th>
		<th width=40%>Description</th>
		<th width=7%>Project</th>
		<th width=7%>Requested By</th>
		<th width=7%>Owner</th>
		<th width=12%>Deployed at</th>
		<th width=7%>Archive</th>
	  </tr>  
      <tbody>
	    <% @deployedtasks.each do |task| %> 	  
          <tr>
		    <td><%= link_to task.title, task_path(task) %></td>
			<td><%= task.description %></td>
			<td><%= task.project.name unless task.project.nil? %></td>
			<td><%= task.requestor.name unless task.requestor.nil?  %></td>
			<td><%= task.owner.name unless task.owner.nil?  %></td>
			<td><%= task.deployed_at.strftime("%d %B, %I:%M%p,%a") %></td>
			<td><%= link_to "Archive", archived_task_path(task) %></td>		
          </tr>
		<% end %>  
      </tbody>
    </table>
  </div>
</div>
 <% else %>
   <p class="text-primary" style="margin-left: 20px;">All Deployed tasks has been archived.</p>
   <br/>
 <% end %> 

app/views/tasks/edit.html.erb
<h1>Editing task</h1>
<div style="margin-left: 30px;">
<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', :back %>
</div>

app/views/tasks/index.html.erb
<script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
<script src="http://code.jquery.com/ui/1.8.21/jquery-ui.min.js"></script>
<script src="jquery.ui.touch-punch.min.js"></script>

<%= image_tag("ncm_logo.jpg", :style => "width: 44px; margin-top: 10px;") %>
<div style="position: absolute; margin-top: -70px; margin-left: 107px;"><h2>NCM Manila</h2></div>
<div style="position: absolute; margin-top: -28px; margin-left: 109px;"><h4>Web Developers</h4></div>
<div style="position: absolute; margin-top: -48px; margin-left: 50px;">
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple117/v4/a6/d2/2c/a6d22ca4-5b4d-a1de-03ac-6a67a81b07fe/source/512x512bb.jpg" style="width:51px;height:51px;">
</div>
<br/><br/>
<h4 style="margin-left: 5px;">Sprint: <%= @current_sprint %></h4>
<div id="divTasks" style="margin-left: 20px;">
  <div class="center">
    <table class="table table-striped table-hover ">
      <tbody>
        <tr>
          <th style="width: 250px;">Stories (<%= @readytasks.count %>)</th>
          <th style="width: 250px;">WIP (<%= @progresstasks.count %>/<%= User.all.length * 2 %>)</th>
          <th style="width: 250px;">Completed (<%= @completedtasks.count %>/<%= Task.current.count - (@deployedtasks.count + @testedtasks.count) %>)</th>
          <th style="width: 250px;">Pushed/Tested (<%= @testedtasks.count %>/<%= Task.current.count - @deployedtasks.count %>)</th>
          <th style="width: 250px;">Deployed (<%= @deployedtasks.count %>/<%= Task.current.count %>)</th>
        </tr>
	  </tbody>	
	  <tbody>	
        <tr style="width: 200px; text-align:center;">
          <td id="colRdy" class="colRdy">
            
            <% @readytasks.each do |task| %>
			  <% if task.urgent == true %>
			    <div class="dragme" id="<%=task.id%>" style="background-color: #F45F49">
			  <% else %>		
                <div class="dragme" id="<%=task.id%>" style="background-color: <%= task.owner.color %>">
			  <% end %>
			  <% if task.sprint_number < @tasks.last.sprint_number %>
			    <b><%= task.sprint_number %></b>
			  <% end %>		
				<div style="font-size: 10px;">
				  <%= link_to task_path(task) do %>	  
			        <%= task.owner.name %>/<%= task.estimate %> hrs./Req: <%= task.requestor.name %>
				  <% end %>	
				</div>  
				<br/>
                <%= task.project.name %> - <%= task.title %>
				<br/><br/>
				<%= link_to "Edit", edit_task_path(task) %>
              </div>
            <%end%>
            
          </td>
          <td id="colProg" class="colProg">
            <% @progresstasks.each do |task| %>
			  <% if task.urgent == true %>
			    <div class="dragme" id="<%=task.id%>" style="background-color: #F45F49">
			  <% else %>		
                <div class="dragme" id="<%=task.id%>" style="background-color: <%= task.owner.color %>">
			  <% end %>
			  <% if task.sprint_number < @tasks.last.sprint_number %>
			    <b><%= task.sprint_number %></b>
			  <% end %>		 
				<div style="font-size: 10px;">
				  <%= link_to task_path(task) do %>	  
			        <%= task.owner.name %>/<%= task.estimate %> hrs./Req: <%= task.requestor.name %>
				  <% end %>	
				  <br/>
				  <%= task.wip_started_date.strftime("%d %B, %I:%M%p,%a") %>
			    </div>	
				<br/>  
                <%= task.project.name %> - <%= task.title %>
				<br/><br/>
				<%= link_to "Edit", edit_task_path(task) %>
              </div>
            <%end%>
          </td>
          <td id="colCompl" class="colCompl">
            <% @completedtasks.each do |task| %>
			  <% if task.urgent == true %>
			    <div class="dragme" id="<%=task.id%>" style="background-color: #F45F49">
			  <% else %>		
                <div class="dragme" id="<%=task.id%>" style="background-color: <%= task.owner.color %>">
			  <% end %>
			  <% if task.sprint_number < @tasks.last.sprint_number %>
			    <b><%= task.sprint_number %></b>
			  <% end %>		 
				<div style="font-size: 10px;">  
			      <%= link_to task_path(task) do %><%= task.owner.name %>/<%= task.estimate %> hrs./Req: <%= task.requestor.name %>
				  <% end %>
				  <br/>
				  <%= task.wip_started_date.strftime("%d %B, %I:%M%p,%a") unless task.wip_started_date.nil? %>
				  <br/>  
				  <%= task.completed_at.strftime("%d %B, %I:%M%p,%a") %>
				</div>
				<br/>	  
                <%= task.project.name %> - <%= task.title %>
				<br/><br/>
				<%= link_to "Edit", edit_task_path(task) %>
              </div>
            <%end%>
          </td>
          <td id="colTest" class="colTest">
            <% @testedtasks.each do |task| %>
			  <% if task.urgent == true %>
			    <div class="dragme" id="<%=task.id%>" style="background-color: #F45F49">
			  <% else %>		
                <div class="dragme" id="<%=task.id%>" style="background-color: <%= task.owner.color %>">
			  <% end %>
			  <% if task.sprint_number < @tasks.last.sprint_number %>
			    <b><%= task.sprint_number %></b>
			  <% end %>		 
			    <div style="font-size: 10px;">
				  <%= link_to task_path(task) do %>	
				    <%= task.owner.name %>/<%= task.estimate %> hrs./Req: <%= task.requestor.name %>
				  <% end %>
				  <br/>
				  <%= task.wip_started_date.strftime("%d %B, %I:%M%p,%a") unless task.wip_started_date.nil? %>
				  <br/>
				  <%= task.tested_at.strftime("%d %B, %I:%M%p,%a") %>
			    </div>
				<br/>	  
                <%= task.project.name %> - <%= task.title %>
				<br/><br/>
				<%= link_to "Edit", edit_task_path(task) %>
              </div>
            <%end%>
          </td>
          <td id="colDepl" class="colDepl">
            <% @deployedtasks.each do |task| %>
			  <% if task.urgent == true %>
			    <div class="dragme" id="<%=task.id%>" style="background-color: #F45F49">
			  <% else %>		
                <div class="dragme" id="<%=task.id%>" style="background-color: <%= task.owner.color %>">
			  <% end %>
			  <% if task.sprint_number < @tasks.last.sprint_number %>
			    <b><%= task.sprint_number %></b>
			  <% end %>
			  <div style="font-size: 10px;">
				<%= link_to task_path(task) do %>  		 
			      <%= task.owner.name %>/<%= task.estimate %> hrs./Req: <%= task.requestor.name %>
				<% end %>  
				  <br/>
				<%= task.wip_started_date.strftime("%d %B, %I:%M%p,%a") unless task.wip_started_date.nil? %>
				<br/>
				<%= task.deployed_at.strftime("%d %B, %I:%M%p,%a") %>
				<br/>
			  </div>
			    <br/>		  
                <%= task.project.name %> - <%= task.title %>
				<br/><br/>
				<%= link_to "Archive", set_archived_task_path(task) %>
              </div>
            <%end%>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/tasks/ongoing.html.erb
<script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
<script src="http://code.jquery.com/ui/1.8.21/jquery-ui.min.js"></script>
<script src="jquery.ui.touch-punch.min.js"></script>

<%= image_tag("ncm_logo.jpg", :style => "width: 44px; margin-top: 10px;") %>
<div style="position: absolute; margin-top: -70px; margin-left: 107px;"><h2>NCM Manila</h2></div>
<div style="position: absolute; margin-top: -28px; margin-left: 109px;"><h4>Web Developers</h4></div>
<div style="position: absolute; margin-top: -48px; margin-left: 50px;">
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple117/v4/a6/d2/2c/a6d22ca4-5b4d-a1de-03ac-6a67a81b07fe/source/512x512bb.jpg" style="width:51px;height:51px;">
</div>
<br/><br/>
<h2>&nbsp;Listing Ongoing Tasks</h2>
<br/>

<h4>&nbsp;&nbsp;Stories</h4>
<% if @readytasks.count > 0 %>
  <div id="divTasks" style="margin-left: 20px; margin-right: 20px;">
    <div class="center">
  	<table class="table table-striped table-hover ">  
  	  <tr class="warning">
  	    <th width=20%>Title</th>
  		<th width=40%>Description</th>
  		<th width=7%>Project</th>
  		<th width=7%>Requested By</th>
  		<th width=7%>Owner</th>
  		<th width=12%>Added at</th>
  		<th width=7%>Edit</th>
  	  </tr>  
        <tbody>
  	    <% @readytasks.each do |task| %> 	  
            <tr>
  		    <td><%= link_to task.title, task_path(task) %></td>
  			<td><%= task.description %></td>
  			<td><%= task.project.name unless task.project.nil? %></td>
  			<td><%= task.requestor.name unless task.requestor.nil?  %></td>
  			<td><%= task.owner.name unless task.owner.nil?  %></td>
  			<td><%= task.updated_at.strftime("%d %B, %I:%M%p,%a") %></td>
  			<td><%= link_to "Edit", edit_task_path(task) %></td>		
            </tr>
  		<% end %>  
        </tbody>
      </table>
    </div>
  </div>
 <% else %>
   <p class="text-primary" style="margin-left: 20px;">All Stories has been processed.</p>
   <br/>
 <% end %> 

<% if @progresstasks.count > 0 %>
<h5>&nbsp;&nbsp;Work In Progress</h5>
<div id="divTasks" style="margin-left: 20px; margin-right: 20px;">
  <div class="center">
	<table class="table table-striped table-hover ">  
	  <tr class="warning">
	    <th width=20%>Title</th>
		<th width=40%>Description</th>
		<th width=7%>Project</th>
		<th width=7%>Requested By</th>
		<th width=7%>Owner</th>
		<th width=12%>Started at</th>
		<th width=7%>Edit</th>
	  </tr>  
      <tbody>
	    <% @progresstasks.each do |task| %> 	  
          <tr>
		    <td><%= link_to task.title, task_path(task) %></td>
			<td><%= task.description %></td>
			<td><%= task.project.name unless task.project.nil? %></td>
			<td><%= task.requestor.name unless task.requestor.nil?  %></td>
			<td><%= task.owner.name unless task.owner.nil?  %></td>
			<td><%= task.wip_started_date.strftime("%d %B, %I:%M%p,%a") %></td>
			<td><%= link_to "Edit", edit_task_path(task) %></td>		
          </tr>
		<% end %>  
      </tbody>
    </table>
  </div>
</div>
 <% else %>
   <p class="text-primary" style="margin-left: 20px;">All WIP has been completed or Stories has not been started.</p>
   <br/>
 <% end %> 

<h5>&nbsp;&nbsp;Completed</h5>
<div id="divTasks" style="margin-left: 20px; margin-right: 20px;">
  <div class="center">
	<table class="table table-striped table-hover ">  
	  <tr class="warning">
	    <th width=20%>Title</th>
		<th width=40%>Description</th>
		<th width=7%>Project</th>
		<th width=7%>Requested By</th>
		<th width=7%>Owner</th>
		<th width=12%>Created at</th>
		<th width=7%>Edit</th>
	  </tr>  
      <tbody>
	    <% @completedtasks.each do |task| %> 	  
          <tr>
		    <td><%= link_to task.title, task_path(task) %></td>
			<td><%= task.description %></td>
			<td><%= task.project.name unless task.project.nil? %></td>
			<td><%= task.requestor.name unless task.requestor.nil?  %></td>
			<td><%= task.owner.name unless task.owner.nil?  %></td>
			<td><%= task.completed_at.strftime("%d %B, %I:%M%p,%a") %></td>
			<td><%= link_to "Edit", edit_task_path(task) %></td>		
          </tr>
		<% end %>  
      </tbody>
    </table>
  </div>
</div>
<h5>&nbsp;&nbsp;Pushed/Tested</h5>
<div id="divTasks" style="margin-left: 20px; margin-right: 20px;">
  <div class="center">
	<table class="table table-striped table-hover ">  
	  <tr class="warning">
	    <th width=20%>Title</th>
		<th width=40%>Description</th>
		<th width=7%>Project</th>
		<th width=7%>Requested By</th>
		<th width=7%>Owner</th>
		<th width=12%>Tested at</th>
		<th width=7%>Edit</th>
	  </tr>  
      <tbody>
	    <% @testedtasks.each do |task| %> 	  
          <tr>
		    <td><%= link_to task.title, task_path(task) %></td>
			<td><%= task.description %></td>
			<td><%= task.project.name unless task.project.nil? %></td>
			<td><%= task.requestor.name unless task.requestor.nil?  %></td>
			<td><%= task.owner.name unless task.owner.nil?  %></td>
			<td><%= task.tested_at.strftime("%d %B, %I:%M%p,%a") %></td>
			<td><%= link_to "Edit", edit_task_path(task) %></td>		
          </tr>
		<% end %>  
      </tbody>
    </table>
  </div>
</div>

app/views/tasks/stories.html.erb
<script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
<script src="http://code.jquery.com/ui/1.8.21/jquery-ui.min.js"></script>
<script src="jquery.ui.touch-punch.min.js"></script>

<%= image_tag("ncm_logo.jpg", :style => "width: 44px; margin-top: 10px;") %>
<div style="position: absolute; margin-top: -70px; margin-left: 107px;"><h2>NCM Manila</h2></div>
<div style="position: absolute; margin-top: -28px; margin-left: 109px;"><h4>Web Developers</h4></div>
<div style="position: absolute; margin-top: -48px; margin-left: 50px;">
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple117/v4/a6/d2/2c/a6d22ca4-5b4d-a1de-03ac-6a67a81b07fe/source/512x512bb.jpg" style="width:51px;height:51px;">
</div>
<br/><br/>
<h2>&nbsp;Listing Future Tasks</small></h2>
<div id="divTasks" style="margin-left: 20px; margin-right: 20px;">
  <div class="center">
	<table class="table table-striped table-hover ">  
	  <tr class="warning">
	    <th>Title</th>
		<th>Description</th>
		<th>Project</th>
		<th>Requested By</th>
		<th>Estimate</th>
		<th>Owner</th>
		<th>Generate</th>
	  </tr>  
      <tbody>
	    <% @tasks.each do |task| %> 	  
          <tr>
		    <td><%= link_to task.title, edit_task_path(task) %></td>
			<td><%= task.description %></td>
			<td><%= task.project.name %></td>
			<td><%= task.requestor.name %></td>
			<%= form_tag generate_sprint_number_task_path(task), multipart: true do %>
			  <% hours = task.estimate.blank? ? '0' : task.estimate %>
			  <td><%= text_field 'estimate', 'estimate_a', :size => 5, :value => hours %></td>
			  <td><%= select('person','person_id',User.all.collect{|c| [c.name, c.id] }, :selected => task.person_id) %></td>
			  <td><%= submit_tag "Start" %></td>
			<% end %>  		
          </tr>
		<% end %>  
      </tbody>
    </table>
  </div>
</div>