config/routes.rb
Taskboard::Application.routes.draw do
  resources :product_owners

  resources :projects

  resources :users

  resources :tasks do
    member do
      get 'set_archived' => :set_archived
      post 'generate_sprint_number' => :generate_sprint_number
    end
    collection do
      match :stories
      match :ongoing
      match :archived
      match :deployed
    end    
  end  
    
  root :to => 'tasks#index'

  match '/tasks/' => 'tasks#index'

  match '/task/new' => 'tasks#new'

  match '/task/:id/update/status' => 'tasks#update_position'
  

end

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "TaskBoard", root_path, :class => "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li><%= link_to 'New Task', new_task_path %> </li>
		<li><%= link_to 'Stories', stories_tasks_path %> </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'New Task', new_task_path %></li>
            <li class="divider"></li>  
            <li><%= link_to 'People', users_path %></li>
			<li><%= link_to 'Product Owners', product_owners_path %></li>
            <li><%= link_to 'Projects', projects_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Reports <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Future Tasks', stories_tasks_path %> </li>			  
			<li><%= link_to 'Ongoing Tasks', ongoing_tasks_path %> </li>  
			<li><%= link_to 'Deployed Tasks', deployed_tasks_path %> </li>
			<li><%= link_to 'Archived Tasks', archived_tasks_path %> </li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Logyou</a></li>
      </ul>
    </div>
  </div>
</nav>